### ISSUE TITLE
Skip the HealthKit Permissions View if the Permissions Are Already Provided

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziTemplateApplication#22]
### Problem

This issue is related to https://github.com/StanfordSpezi/SpeziHealthKit/issues/6: It would be ideal of the HealthKit onboarding step is skipped when the permission for the current HealthKit types has already been provided. 

### Solution

Once https://github.com/StanfordSpezi/SpeziHealthKit/issues/6 is closed, we should add a conditional statement to the onboarding flow of the previous onbarodhing step to conditionally show the HealthKit onboarding flow in case the permission have already been provided.

### Additional context

Please reference to https://github.com/StanfordSpezi/SpeziHealthKit/issues/6 about more information about the required changes in the HealthKit module.
We are happy to provide guidance and help if you want to work on this issue. Feel free to use the comment section under this issue to discuss your possible approach and how you plan to address the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
Addressed in #26.
