### ISSUE TITLE
Bug report:Failed to add SpeziFirebase And SpeziAccount package

### ISSUE THREAD

**Issue by Shaikmasaqhlain888** [StanfordSpezi/SpeziTemplateApplication#88]
### Description

I was trying to add "SpeziFirebase" to my project using the link:https://github.com/StanfordSpezi/Spezifirebase, But it says Package resolution Failed. 

<img width="1512" alt="Screenshot 2024-10-03 at 1 37 54 PM" src="https://github.com/user-attachments/assets/9fe1d49e-6eb4-4d9f-83e6-1f7c8579eae3">

### Reproduction

Just try to add the SpeziFirebase package from a GitHub Link and click on the add, It will  prompt the bug.

### Expected behavior

SpeziFirebase should be added as a dependency without any errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
This may be the same issue from https://github.com/StanfordSpezi/SpeziTemplateApplication/issues/87. There is a temporary solution mentioned in the thread there, and a permanent fix in process. Sorry for the inconvenience!

cc: @PSchmiedmayer

**Comment by Shaikmasaqhlain888** [comment]
Thanks for the Response, I have tried adding the Pre-Release version of "SpeziFirebase" and I was able to add the package But Now I am facing this issue " No such module "FirebaseFirestore " in the SpeziFirebase->SpeziFirestore->
<img width="1512" alt="Screenshot 2024-10-21 at 11 05 17 AM" src="https://github.com/user-attachments/assets/89c22bcc-52fe-490d-8538-1ed18366b2d3">
Resources-> DocumentReference+AsyncWait File. Can you please help where I need to change things to fix this issue.

**Comment by PSchmiedmayer** [comment]
@Shaikmasaqhlain888 The package should incorporate the Firestore Package; I am wondering if this is an Xcode caching error. Can you reset your package caches, update the dependencies to the latest versions, and clear your build folder + build issues and try it again with a clean build?

**Comment by Shaikmasaqhlain888** [comment]
I have tried Cleaning the build, Derived Data, Cache and also updated all the dependencies to the latest versions but I am Still facing this error

**Comment by PSchmiedmayer** [comment]
Can you share a link to the project on GitHub so we can take a look at it and see if we can replicate the issue?

**Comment by Shaikmasaqhlain888** [comment]
Here is my project link: https://github.com/Shaikmasaqhlain888/HealthDataMonitor

**Comment by PSchmiedmayer** [comment]
@Shaikmasaqhlain888 Thank you for sharing the setup!

I don't see SpeziFirebase in the current project setup; it seems to build fine for now. Can you share your state that is failing, e.g., in a feature branch to check it out and replicate the build error?

If we can't quickly identify the error might might also be helpful to replicate elements with a simple GitHub action demonstrating the error on a newly created runner.

**Comment by Shaikmasaqhlain888** [comment]
It's not in the project yet as I have deleted it before adding it again to  see if that helps. I can direct to replicate the issue, You can add "SpeziFirebase" package and try to run the project you will find that error in the console in the file that I have mentioned earlier.

**Comment by Shaikmasaqhlain888** [comment]
https://github.com/Shaikmasaqhlain888/HealthDataMonitor. 

Hello @PSchmiedmayer , I have added the SpeziFirebase in the current Repository and You should be able to see it. I am still getting the same error. Also, If I use any older versions would that help me get my project working? until this error is solved in newer version.

**Comment by PSchmiedmayer** [comment]
@Shaikmasaqhlain888 I just took a look at the issue: It seems like the issue originates from you aiming to utilize SpeziFirebase and SpeziAccount on a watchOS target. Both targets currently don't support watchOS, and Firebase also doesn't support some of the elements that SpeziFirebase is using, such as Firebase Datastore: https://firebase.google.com/docs/ios/learn-more.

I think the solution would be to add both targets to your iOS application while communicating anything between the watch and the iOS application using watch connectivity. It is important to note that you don't need to run an app on the Apple Watch to collect data using HealthKit (even elements collected on the Apple Watch are synced to the phone).

Therefore, I would suggest positioning the data collection, authentication/authorization, as well as Firebase interaction right on the phone. If you need a watchOS application, I would suggest watch connectivity to communicate with the iOS application and render your relevant UI on there.
